name: crypto_owl
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #google

  #state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  #widget
  lottie: ^2.6.0
  #network
  http: ^1.1.0
  async: ^2.11.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  json_annotation: ^4.0.0
  internet_connection_checker: ^1.0.0+1
  #error
  either_dart: ^1.0.0
  #remote API
  #test
  bloc_test: ^9.1.4

  #locale cache
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3
  mockito: ^5.4.2
flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
